# Generated by Django 5.2.5 on 2025-11-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('startup', 'Startup'), ('incubadora', 'Incubadora')], default='startup', help_text='Type of user account', max_length=20),
        ),
    ]
