# Generated by Django 5.2.5 on 2025-11-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('startup', 'Startup'), ('incubator', 'Incubator')], default='startup', help_text='Type of user account', max_length=20),
        ),
    ]
