# Generated by Django 5.2.5 on 2025-11-24 02:58

from django.db import migrations


def migrate_incubadora_to_incubator(apps, schema_editor):
    """Update existing 'incubadora' user_type values to 'incubator'"""
    Profile = apps.get_model('users', 'Profile')
    Profile.objects.filter(user_type='incubadora').update(user_type='incubator')


def reverse_migrate(apps, schema_editor):
    """Reverse migration: update 'incubator' back to 'incubadora'"""
    Profile = apps.get_model('users', 'Profile')
    Profile.objects.filter(user_type='incubator').update(user_type='incubadora')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user_type'),
    ]

    operations = [
        migrations.RunPython(migrate_incubadora_to_incubator, reverse_migrate),
    ]
