# Generated by Django 5.2.5 on 2025-11-29 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_migrate_incubadora_to_incubator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('fintech', 'FinTech'), ('healthtech', 'HealthTech'), ('edtech', 'EdTech'), ('ecommerce', 'E-commerce'), ('saas', 'SaaS'), ('ai_ml', 'AI/ML'), ('blockchain', 'Blockchain'), ('marketplace', 'Marketplace'), ('other', 'Other')], max_length=50, null=True)),
                ('logo_url', models.URLField(blank=True, help_text='URL to company logo in GCS', null=True)),
                ('is_mock_data', models.BooleanField(default=True, help_text='Indicates if this is mock/sample data')),
                ('profile', models.OneToOneField(limit_choices_to={'user_type': 'startup'}, on_delete=django.db.models.deletion.CASCADE, related_name='startup', to='users.profile')),
            ],
            options={
                'verbose_name': 'Startup',
                'verbose_name_plural': 'Startups',
            },
        ),
    ]
