# Generated by Django 5.2.5 on 2025-11-29 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_startup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('trl_level', models.IntegerField(choices=[(1, 'TRL 1'), (2, 'TRL 2'), (3, 'TRL 3'), (4, 'TRL 4'), (5, 'TRL 5'), (6, 'TRL 6'), (7, 'TRL 7'), (8, 'TRL 8'), (9, 'TRL 9')], help_text='Technology Readiness Level (1-9)')),
                ('description', models.TextField(help_text='Description of the evidence and what it demonstrates')),
                ('file', models.FileField(blank=True, help_text='Evidence file (PDF, image, video, etc.)', null=True, upload_to='evidence/%Y/%m/')),
                ('file_url', models.URLField(blank=True, help_text='URL to evidence file in cloud storage (e.g., GCS)', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Approval status of this evidence', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Notes from reviewer about this evidence', null=True)),
                ('startup', models.ForeignKey(help_text='Startup that owns this evidence', on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='users.startup')),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidences',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['startup', 'trl_level'], name='users_evide_startup_f24df4_idx'), models.Index(fields=['status'], name='users_evide_status_114a07_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('period_date', models.DateField(help_text='Date representing the period (usually month-end)')),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue for the period', max_digits=15)),
                ('costs', models.DecimalField(decimal_places=2, default=0.0, help_text='Total costs/expenses for the period', max_digits=15)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Cash balance at the end of the period', max_digits=15)),
                ('monthly_burn', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly burn rate (cash spent per month)', max_digits=15)),
                ('notes', models.TextField(blank=True, help_text="Additional notes about this period's finances", null=True)),
                ('startup', models.ForeignKey(help_text='Startup that owns this financial data', on_delete=django.db.models.deletion.CASCADE, related_name='financial_inputs', to='users.startup')),
            ],
            options={
                'verbose_name': 'Financial Input',
                'verbose_name_plural': 'Financial Inputs',
                'ordering': ['-period_date'],
                'indexes': [models.Index(fields=['startup', 'period_date'], name='users_finan_startup_e3e038_idx')],
                'unique_together': {('startup', 'period_date')},
            },
        ),
        migrations.CreateModel(
            name='InvestorPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('investor_name', models.CharField(help_text='Name of the investor or investment firm', max_length=255)),
                ('investor_email', models.EmailField(blank=True, help_text='Contact email for the investor', max_length=254, null=True)),
                ('stage', models.CharField(choices=[('CONTACTED', 'Initial Contact'), ('PITCH_SENT', 'Pitch Deck Sent'), ('MEETING_SCHEDULED', 'Meeting Scheduled'), ('DUE_DILIGENCE', 'Due Diligence'), ('TERM_SHEET', 'Term Sheet Negotiation'), ('COMMITTED', 'Committed'), ('DECLINED', 'Declined')], default='CONTACTED', help_text='Current stage of the investor relationship', max_length=30)),
                ('ticket_size', models.DecimalField(blank=True, decimal_places=2, help_text='Expected or committed investment amount (USD)', max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this investor relationship', null=True)),
                ('next_action_date', models.DateField(blank=True, help_text='Date for next scheduled action/follow-up', null=True)),
                ('startup', models.ForeignKey(help_text='Startup that owns this investor relationship', on_delete=django.db.models.deletion.CASCADE, related_name='investor_pipeline', to='users.startup')),
            ],
            options={
                'verbose_name': 'Investor Pipeline Entry',
                'verbose_name_plural': 'Investor Pipeline',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['startup', 'stage'], name='users_inves_startup_d9393b_idx')],
            },
        ),
    ]
