# Generated by Django 5.2.5 on 2025-11-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_evidence_financialinput_investorpipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='True when user completes the onboarding wizard'),
        ),
    ]
