# Generated by Django 5.2.5 on 2025-12-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_startup_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='crl_level',
            field=models.IntegerField(blank=True, choices=[(1, 'CRL 1'), (2, 'CRL 2'), (3, 'CRL 3'), (4, 'CRL 4'), (5, 'CRL 5'), (6, 'CRL 6'), (7, 'CRL 7'), (8, 'CRL 8'), (9, 'CRL 9')], help_text='Commercial Readiness Level (1-9)', null=True),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['startup', 'crl_level'], name='users_evide_startup_633c72_idx'),
        ),
    ]
