# Generated by Django 5.2.5 on 2025-12-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_evidence_crl_level_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='evidence',
            name='users_evide_startup_f24df4_idx',
        ),
        migrations.RemoveIndex(
            model_name='evidence',
            name='users_evide_startup_633c72_idx',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='crl_level',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='file',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='trl_level',
        ),
        migrations.AddField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('TRL', 'Technology Readiness Level'), ('CRL', 'Commercial Readiness Level')], default='TRL', help_text='Type of readiness level (TRL or CRL)', max_length=10),
        ),
        migrations.AddField(
            model_name='evidence',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6'), (7, 'Level 7'), (8, 'Level 8'), (9, 'Level 9')], default=1, help_text='Readiness Level (1-9)'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['startup', 'evidence_type', 'level'], name='users_evide_startup_c1f432_idx'),
        ),
    ]
