# Generated by Django 5.2.5 on 2025-12-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_evidence_users_evide_startup_f24df4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='evidence',
            name='users_evide_startup_c1f432_idx',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='evidence_type',
            new_name='type',
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['startup', 'type', 'level'], name='users_evide_startup_429400_idx'),
        ),
    ]
