# Generated by Django 5.2.5 on 2025-12-03 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_evidence_users_evide_startup_c1f432_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Name of the fundraising round (e.g., 'Seed', 'Series A')", max_length=100)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Target amount to raise for this round (USD)', max_digits=15, null=True)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount already raised for this round (USD)', max_digits=15)),
                ('is_open', models.BooleanField(default=True, help_text='Indicates if the fundraising round is currently open')),
                ('start_date', models.DateField(blank=True, help_text='Date when the round officially started', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Date when the round is expected to close or closed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this fundraising round', null=True)),
                ('startup', models.ForeignKey(help_text='Startup that owns this fundraising round', on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='users.startup')),
            ],
            options={
                'verbose_name': 'Round',
                'verbose_name_plural': 'Rounds',
                'ordering': ['-start_date', '-created'],
                'indexes': [models.Index(fields=['startup', 'is_open'], name='users_round_startup_985eda_idx')],
                'unique_together': {('startup', 'name')},
            },
        ),
    ]
