# Generated by Django 5.2.5 on 2025-12-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='financial_projections',
            field=models.JSONField(blank=True, default=dict, help_text='Quarterly financial projections (revenue, COGS, OPEX)', null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('fintech', 'FinTech'), ('healthtech', 'HealthTech'), ('edtech', 'EdTech'), ('ecommerce', 'E-commerce'), ('saas', 'SaaS'), ('ai_ml', 'AI/ML'), ('blockchain', 'Blockchain'), ('Marketplace', 'Marketplace'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
