# Generated by Django 5.2.5 on 2025-12-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_startup_financial_projections_alter_startup_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='financial_projections',
        ),
    ]
