# Generated by Django 5.2.5 on 2025-12-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_startup_financial_projections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the evidence and what it demonstrates', null=True),
        ),
    ]
