# Generated by Django 5.2.5 on 2025-12-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_startup_is_mock_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='CRL_level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6'), (7, 'Level 7'), (8, 'Level 8'), (9, 'Level 9')], default=1, help_text='Current Commercial Readiness Level (1-9)'),
        ),
        migrations.AddField(
            model_name='startup',
            name='TRL_level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6'), (7, 'Level 7'), (8, 'Level 8'), (9, 'Level 9')], default=1, help_text='Current Technology Readiness Level (1-9)'),
        ),
    ]
