# Generated by Django 5.2.5 on 2025-12-03 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_startup_crl_level_startup_trl_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadinessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('TRL', 'Technology Readiness Level'), ('CRL', 'Commercial Readiness Level')], default='TRL', help_text='Type of readiness level (TRL or CRL)', max_length=10)),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6'), (7, 'Level 7'), (8, 'Level 8'), (9, 'Level 9')], help_text='Level number (1-9)')),
                ('title', models.CharField(help_text="Title of this level (e.g., 'Proof of Concept')", max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle or brief description', max_length=255, null=True)),
                ('startup', models.ForeignKey(help_text='Startup that owns this readiness level', on_delete=django.db.models.deletion.CASCADE, related_name='readiness_levels', to='users.startup')),
            ],
            options={
                'verbose_name': 'Readiness Level',
                'verbose_name_plural': 'Readiness Levels',
                'ordering': ['type', 'level'],
                'unique_together': {('startup', 'type', 'level')},
            },
        ),
    ]
