# Generated by Django 5.2.5 on 2025-12-04 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_readinesslevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incubator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the Incubator', max_length=255)),
                ('profile', models.OneToOneField(limit_choices_to={'user_type': 'incubator'}, on_delete=django.db.models.deletion.CASCADE, related_name='incubator', to='users.profile')),
            ],
            options={
                'verbose_name': 'Incubator',
                'verbose_name_plural': 'Incubators',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('required_technologies', models.TextField(help_text='Comma-separated list of technologies or description')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CONCLUDED', 'Concluded')], default='OPEN', max_length=20)),
                ('incubator', models.ForeignKey(help_text='Incubator that launched this challenge', on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='users.incubator')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
            },
        ),
        migrations.AddField(
            model_name='startup',
            name='incubators',
            field=models.ManyToManyField(blank=True, help_text='Incubators that this startup is associated with', related_name='startups', to='users.incubator'),
        ),
        migrations.CreateModel(
            name='IncubatorMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('INVESTOR', 'Investor'), ('MENTOR', 'Mentor'), ('BOTH', 'Both')], default='MENTOR', help_text='Role of the person in the incubator', max_length=20)),
                ('incubator', models.ForeignKey(help_text='Incubator this person belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.incubator')),
            ],
            options={
                'verbose_name': 'Incubator Member',
                'verbose_name_plural': 'Incubator Members',
            },
        ),
        migrations.CreateModel(
            name='ChallengeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text_solution', models.TextField(help_text='Text description of the solution')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.challenge')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_applications', to='users.startup')),
            ],
            options={
                'verbose_name': 'Challenge Application',
                'verbose_name_plural': 'Challenge Applications',
                'unique_together': {('challenge', 'startup')},
            },
        ),
    ]
