# Generated by Django 5.2.5 on 2025-12-04 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_incubator_challenge_startup_incubators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorpipeline',
            name='round',
            field=models.ForeignKey(blank=True, help_text='Fundraising round this investor is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='users.round'),
        ),
    ]
