# Generated by Django 5.2.5 on 2025-12-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_investorpipeline_round'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set(),
        ),
    ]
