# Generated by Django 5.2.5 on 2025-12-04 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_round_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='readiness_level',
            field=models.ForeignKey(blank=True, help_text='Specific readiness level definition this evidence supports', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='users.readinesslevel'),
        ),
    ]
