# Generated by Django 5.2.5 on 2025-12-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_evidence_readiness_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubator',
            name='profile_complete',
            field=models.BooleanField(default=False, help_text='True when incubator profile is complete'),
        ),
    ]
