# Generated by Django 5.2.5 on 2025-12-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_incubator_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubator',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the incubator thesis and focus', null=True),
        ),
        migrations.AddField(
            model_name='incubator',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to incubator logo', null=True),
        ),
    ]
