# Generated by Django 5.2.5 on 2025-12-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignfinancials',
            name='current_cash_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current cash balance available', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='campaignfinancials',
            name='financial_projections',
            field=models.JSONField(blank=True, default=dict, help_text="Quarterly financial projections: { 'q1': { 'revenue': 0, 'cogs': 0, 'opex': 0 }, 'q2': {...}, 'q3': {...}, 'q4': {...} }"),
        ),
        migrations.AddField(
            model_name='campaignfinancials',
            name='monthly_burn_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly burn rate (cash spent per month)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='campaignfinancials',
            name='pre_money_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pre-money valuation of the startup', max_digits=15, null=True),
        ),
    ]
