# Generated by Django 5.2.5 on 2025-12-03 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignfinancials_current_cash_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g., 'Pre-Seed', 'Seed', 'Series A', 'Bridge'", max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pre_money_valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('is_current', models.BooleanField(default=False, help_text='Is this the current round for the wizard?')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='campaigns.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('CONTACTED', 'Contacted'), ('MEETING', 'Meeting'), ('DUE_DILIGENCE', 'Due Diligence'), ('COMMITTED', 'Committed')], default='CONTACTED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='campaigns.investmentround')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
