# Generated by Django 5.2.5 on 2025-12-04 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_investmentround_investor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sheet_data', models.JSONField(default=dict, help_text="Structure: { 'config': {...}, 'grid_rows': [...] }")),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_sheet', to='campaigns.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
