# Generated by Django 5.2.5 on 2025-12-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_financialsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentround',
            name='close_date',
            field=models.DateField(blank=True, help_text='Date when the round was closed', null=True),
        ),
    ]
