# Generated by Django 5.2.5 on 2025-12-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_investmentround_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
