# Generated by Django 5.2.5 on 2025-12-04 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_investor_email'),
        ('users', '0019_investorpipeline_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='name',
        ),
        migrations.AddField(
            model_name='investor',
            name='incubator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='users.incubator'),
            preserve_default=False,
        ),
    ]
