# Generated by Django 5.2.5 on 2025-12-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_remove_investor_email_remove_investor_name_and_more'),
        ('users', '0019_investorpipeline_round'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investor',
            unique_together={('round', 'incubator')},
        ),
    ]
