# Generated by Django 5.2.5 on 2025-12-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_alter_investor_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentround',
            name='close_date',
        ),
        migrations.AddField(
            model_name='investmentround',
            name='actual_close_date',
            field=models.DateField(blank=True, help_text='Date when the round was actually closed', null=True),
        ),
        migrations.AddField(
            model_name='investmentround',
            name='launch_date',
            field=models.DateField(blank=True, help_text='Date when the round officially opened', null=True),
        ),
        migrations.AddField(
            model_name='investmentround',
            name='target_close_date',
            field=models.DateField(blank=True, help_text='Target deadline communicated to investors', null=True),
        ),
    ]
