# Generated by Django 5.2.5 on 2025-12-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_remove_investmentround_close_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='status',
            field=models.CharField(choices=[('CONTACTED', 'Contacted'), ('PITCH_SENT', 'Pitch Sent'), ('MEETING_SCHEDULED', 'Meeting Scheduled'), ('DUE_DILIGENCE', 'Due Diligence'), ('TERM_SHEET', 'Term Sheet'), ('COMMITTED', 'Committed')], default='CONTACTED', max_length=20),
        ),
    ]
