# Generated by Django 5.2.5 on 2025-12-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_alter_investor_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investor',
            unique_together=set(),
        ),
    ]
